<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="memm\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="mr\FreeLifetime.fs" />
    <Compile Include="mr\MR.fs" />
    <Compile Include="files\ReadFile.fs" />
	<Compile Include="compiler\lexer\Lexer.fs" />
	<Compile Include="compiler\parser_lib\MLW\MonadicLambdaWalkingTypeInference.fs" />
	<Compile Include="compiler\parser_lib\Psictre.fs" />
	<Compile Include="compiler\parser\BaseParser.fs" />
	<Compile Include="compiler\parser\Expr.fs" />
	<Compile Include="compiler\parser\Defvar.fs" />
    <Compile Include="compiler\SimpleScope.fs" />
    <Compile Include="Test.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
	
  <ItemGroup>
	<None Include="mlir\*\*" />
	<None Include="mlir\*" />
  </ItemGroup>

</Project>
