name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notes to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
